// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg/consumer/FetchMessage.proto

package com.cookienats.common.papimq.protos.msg.consumer;

public final class FetchMessage {
  private FetchMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FetchMessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FetchMessageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string topicName = 1;</code>
     */
    String getTopicName();
    /**
     * <code>string topicName = 1;</code>
     */
    com.google.protobuf.ByteString
        getTopicNameBytes();

    /**
     * <code>string subscriberName = 2;</code>
     */
    String getSubscriberName();
    /**
     * <code>string subscriberName = 2;</code>
     */
    com.google.protobuf.ByteString
        getSubscriberNameBytes();
  }
  /**
   * Protobuf type {@code FetchMessageRequest}
   */
  public  static final class FetchMessageRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FetchMessageRequest)
      FetchMessageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FetchMessageRequest.newBuilder() to construct.
    private FetchMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FetchMessageRequest() {
      topicName_ = "";
      subscriberName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FetchMessageRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              topicName_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              subscriberName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FetchMessage.internal_static_FetchMessageRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FetchMessage.internal_static_FetchMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FetchMessageRequest.class, Builder.class);
    }

    public static final int TOPICNAME_FIELD_NUMBER = 1;
    private volatile Object topicName_;
    /**
     * <code>string topicName = 1;</code>
     */
    public String getTopicName() {
      Object ref = topicName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        topicName_ = s;
        return s;
      }
    }
    /**
     * <code>string topicName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicNameBytes() {
      Object ref = topicName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        topicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBSCRIBERNAME_FIELD_NUMBER = 2;
    private volatile Object subscriberName_;
    /**
     * <code>string subscriberName = 2;</code>
     */
    public String getSubscriberName() {
      Object ref = subscriberName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subscriberName_ = s;
        return s;
      }
    }
    /**
     * <code>string subscriberName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubscriberNameBytes() {
      Object ref = subscriberName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subscriberName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTopicNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topicName_);
      }
      if (!getSubscriberNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subscriberName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTopicNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topicName_);
      }
      if (!getSubscriberNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subscriberName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FetchMessageRequest)) {
        return super.equals(obj);
      }
      FetchMessageRequest other = (FetchMessageRequest) obj;

      boolean result = true;
      result = result && getTopicName()
          .equals(other.getTopicName());
      result = result && getSubscriberName()
          .equals(other.getSubscriberName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOPICNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTopicName().hashCode();
      hash = (37 * hash) + SUBSCRIBERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriberName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FetchMessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FetchMessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FetchMessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FetchMessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FetchMessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FetchMessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FetchMessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FetchMessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FetchMessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FetchMessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FetchMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FetchMessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FetchMessageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FetchMessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FetchMessageRequest)
        FetchMessageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FetchMessage.internal_static_FetchMessageRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FetchMessage.internal_static_FetchMessageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FetchMessageRequest.class, Builder.class);
      }

      // Construct using com.cookienats.common.papimq.protos.msg.consumer.FetchMessage.FetchMessageRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        topicName_ = "";

        subscriberName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FetchMessage.internal_static_FetchMessageRequest_descriptor;
      }

      @Override
      public FetchMessageRequest getDefaultInstanceForType() {
        return FetchMessageRequest.getDefaultInstance();
      }

      @Override
      public FetchMessageRequest build() {
        FetchMessageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FetchMessageRequest buildPartial() {
        FetchMessageRequest result = new FetchMessageRequest(this);
        result.topicName_ = topicName_;
        result.subscriberName_ = subscriberName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FetchMessageRequest) {
          return mergeFrom((FetchMessageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FetchMessageRequest other) {
        if (other == FetchMessageRequest.getDefaultInstance()) return this;
        if (!other.getTopicName().isEmpty()) {
          topicName_ = other.topicName_;
          onChanged();
        }
        if (!other.getSubscriberName().isEmpty()) {
          subscriberName_ = other.subscriberName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FetchMessageRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FetchMessageRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object topicName_ = "";
      /**
       * <code>string topicName = 1;</code>
       */
      public String getTopicName() {
        Object ref = topicName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          topicName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string topicName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTopicNameBytes() {
        Object ref = topicName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          topicName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topicName = 1;</code>
       */
      public Builder setTopicName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topicName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topicName = 1;</code>
       */
      public Builder clearTopicName() {
        
        topicName_ = getDefaultInstance().getTopicName();
        onChanged();
        return this;
      }
      /**
       * <code>string topicName = 1;</code>
       */
      public Builder setTopicNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topicName_ = value;
        onChanged();
        return this;
      }

      private Object subscriberName_ = "";
      /**
       * <code>string subscriberName = 2;</code>
       */
      public String getSubscriberName() {
        Object ref = subscriberName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          subscriberName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string subscriberName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSubscriberNameBytes() {
        Object ref = subscriberName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          subscriberName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subscriberName = 2;</code>
       */
      public Builder setSubscriberName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subscriberName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subscriberName = 2;</code>
       */
      public Builder clearSubscriberName() {
        
        subscriberName_ = getDefaultInstance().getSubscriberName();
        onChanged();
        return this;
      }
      /**
       * <code>string subscriberName = 2;</code>
       */
      public Builder setSubscriberNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subscriberName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FetchMessageRequest)
    }

    // @@protoc_insertion_point(class_scope:FetchMessageRequest)
    private static final FetchMessageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FetchMessageRequest();
    }

    public static FetchMessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FetchMessageRequest>
        PARSER = new com.google.protobuf.AbstractParser<FetchMessageRequest>() {
      @Override
      public FetchMessageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchMessageRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FetchMessageRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FetchMessageRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public FetchMessageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FetchMessageResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FetchMessageResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CommonResult result = 1;</code>
     */
    int getResultValue();
    /**
     * <code>.CommonResult result = 1;</code>
     */
    com.cookienats.common.papimq.protos.common.Result.CommonResult getResult();

    /**
     * <code>int64 requestId = 2;</code>
     */
    long getRequestId();

    /**
     * <pre>
     *二进制消息
     * </pre>
     *
     * <code>bytes message = 3;</code>
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code FetchMessageResponse}
   */
  public  static final class FetchMessageResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FetchMessageResponse)
      FetchMessageResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FetchMessageResponse.newBuilder() to construct.
    private FetchMessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FetchMessageResponse() {
      result_ = 0;
      requestId_ = 0L;
      message_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FetchMessageResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 16: {

              requestId_ = input.readInt64();
              break;
            }
            case 26: {

              message_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FetchMessage.internal_static_FetchMessageResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FetchMessage.internal_static_FetchMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FetchMessageResponse.class, Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.CommonResult result = 1;</code>
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.CommonResult result = 1;</code>
     */
    public com.cookienats.common.papimq.protos.common.Result.CommonResult getResult() {
      @SuppressWarnings("deprecation")
      com.cookienats.common.papimq.protos.common.Result.CommonResult result = com.cookienats.common.papimq.protos.common.Result.CommonResult.valueOf(result_);
      return result == null ? com.cookienats.common.papimq.protos.common.Result.CommonResult.UNRECOGNIZED : result;
    }

    public static final int REQUESTID_FIELD_NUMBER = 2;
    private long requestId_;
    /**
     * <code>int64 requestId = 2;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString message_;
    /**
     * <pre>
     *二进制消息
     * </pre>
     *
     * <code>bytes message = 3;</code>
     */
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != com.cookienats.common.papimq.protos.common.Result.CommonResult.SYSTEM_ERROR.getNumber()) {
        output.writeEnum(1, result_);
      }
      if (requestId_ != 0L) {
        output.writeInt64(2, requestId_);
      }
      if (!message_.isEmpty()) {
        output.writeBytes(3, message_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != com.cookienats.common.papimq.protos.common.Result.CommonResult.SYSTEM_ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, requestId_);
      }
      if (!message_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FetchMessageResponse)) {
        return super.equals(obj);
      }
      FetchMessageResponse other = (FetchMessageResponse) obj;

      boolean result = true;
      result = result && result_ == other.result_;
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FetchMessageResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FetchMessageResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FetchMessageResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FetchMessageResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FetchMessageResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FetchMessageResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FetchMessageResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FetchMessageResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FetchMessageResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FetchMessageResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FetchMessageResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FetchMessageResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FetchMessageResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FetchMessageResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FetchMessageResponse)
        FetchMessageResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FetchMessage.internal_static_FetchMessageResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FetchMessage.internal_static_FetchMessageResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FetchMessageResponse.class, Builder.class);
      }

      // Construct using com.cookienats.common.papimq.protos.msg.consumer.FetchMessage.FetchMessageResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        requestId_ = 0L;

        message_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FetchMessage.internal_static_FetchMessageResponse_descriptor;
      }

      @Override
      public FetchMessageResponse getDefaultInstanceForType() {
        return FetchMessageResponse.getDefaultInstance();
      }

      @Override
      public FetchMessageResponse build() {
        FetchMessageResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FetchMessageResponse buildPartial() {
        FetchMessageResponse result = new FetchMessageResponse(this);
        result.result_ = result_;
        result.requestId_ = requestId_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FetchMessageResponse) {
          return mergeFrom((FetchMessageResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FetchMessageResponse other) {
        if (other == FetchMessageResponse.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FetchMessageResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FetchMessageResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ = 0;
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public int getResultValue() {
        return result_;
      }
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public Builder setResultValue(int value) {
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public com.cookienats.common.papimq.protos.common.Result.CommonResult getResult() {
        @SuppressWarnings("deprecation")
        com.cookienats.common.papimq.protos.common.Result.CommonResult result = com.cookienats.common.papimq.protos.common.Result.CommonResult.valueOf(result_);
        return result == null ? com.cookienats.common.papimq.protos.common.Result.CommonResult.UNRECOGNIZED : result;
      }
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public Builder setResult(com.cookienats.common.papimq.protos.common.Result.CommonResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private long requestId_ ;
      /**
       * <code>int64 requestId = 2;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>int64 requestId = 2;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestId = 2;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *二进制消息
       * </pre>
       *
       * <code>bytes message = 3;</code>
       */
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <pre>
       *二进制消息
       * </pre>
       *
       * <code>bytes message = 3;</code>
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *二进制消息
       * </pre>
       *
       * <code>bytes message = 3;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FetchMessageResponse)
    }

    // @@protoc_insertion_point(class_scope:FetchMessageResponse)
    private static final FetchMessageResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FetchMessageResponse();
    }

    public static FetchMessageResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FetchMessageResponse>
        PARSER = new com.google.protobuf.AbstractParser<FetchMessageResponse>() {
      @Override
      public FetchMessageResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchMessageResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FetchMessageResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FetchMessageResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public FetchMessageResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchMessageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FetchMessageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FetchMessageResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FetchMessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037msg/consumer/FetchMessage.proto\032\023commo" +
      "n/Result.proto\"@\n\023FetchMessageRequest\022\021\n" +
      "\ttopicName\030\001 \001(\t\022\026\n\016subscriberName\030\002 \001(\t" +
      "\"Y\n\024FetchMessageResponse\022\035\n\006result\030\001 \001(\016" +
      "2\r.CommonResult\022\021\n\trequestId\030\002 \001(\003\022\017\n\007me" +
      "ssage\030\003 \001(\014B2\n0com.cookienats.common.pap" +
      "imq.protos.msg.consumerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cookienats.common.papimq.protos.common.Result.getDescriptor(),
        }, assigner);
    internal_static_FetchMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FetchMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FetchMessageRequest_descriptor,
        new String[] { "TopicName", "SubscriberName", });
    internal_static_FetchMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FetchMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FetchMessageResponse_descriptor,
        new String[] { "Result", "RequestId", "Message", });
    com.cookienats.common.papimq.protos.common.Result.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
