// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg/consumer/ReportConsumeResult.proto

package com.cookienats.common.papimq.protos.msg.consumer;

public final class ReportConsumeResult {
  private ReportConsumeResult() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReportConsumeResultRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReportConsumeResultRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 requestId = 1;</code>
     */
    long getRequestId();

    /**
     * <code>string topicName = 2;</code>
     */
    String getTopicName();
    /**
     * <code>string topicName = 2;</code>
     */
    com.google.protobuf.ByteString
        getTopicNameBytes();

    /**
     * <code>string subscriberName = 3;</code>
     */
    String getSubscriberName();
    /**
     * <code>string subscriberName = 3;</code>
     */
    com.google.protobuf.ByteString
        getSubscriberNameBytes();

    /**
     * <pre>
     *消息消费结果
     * </pre>
     *
     * <code>.ConsumeResult consumeResult = 4;</code>
     */
    int getConsumeResultValue();
    /**
     * <pre>
     *消息消费结果
     * </pre>
     *
     * <code>.ConsumeResult consumeResult = 4;</code>
     */
    com.cookienats.common.papimq.protos.common.Enums.ConsumeResult getConsumeResult();
  }
  /**
   * Protobuf type {@code ReportConsumeResultRequest}
   */
  public  static final class ReportConsumeResultRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReportConsumeResultRequest)
      ReportConsumeResultRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReportConsumeResultRequest.newBuilder() to construct.
    private ReportConsumeResultRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportConsumeResultRequest() {
      requestId_ = 0L;
      topicName_ = "";
      subscriberName_ = "";
      consumeResult_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReportConsumeResultRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              requestId_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              topicName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              subscriberName_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              consumeResult_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReportConsumeResult.internal_static_ReportConsumeResultRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReportConsumeResult.internal_static_ReportConsumeResultRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReportConsumeResultRequest.class, Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>int64 requestId = 1;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int TOPICNAME_FIELD_NUMBER = 2;
    private volatile Object topicName_;
    /**
     * <code>string topicName = 2;</code>
     */
    public String getTopicName() {
      Object ref = topicName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        topicName_ = s;
        return s;
      }
    }
    /**
     * <code>string topicName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicNameBytes() {
      Object ref = topicName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        topicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBSCRIBERNAME_FIELD_NUMBER = 3;
    private volatile Object subscriberName_;
    /**
     * <code>string subscriberName = 3;</code>
     */
    public String getSubscriberName() {
      Object ref = subscriberName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subscriberName_ = s;
        return s;
      }
    }
    /**
     * <code>string subscriberName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubscriberNameBytes() {
      Object ref = subscriberName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subscriberName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSUMERESULT_FIELD_NUMBER = 4;
    private int consumeResult_;
    /**
     * <pre>
     *消息消费结果
     * </pre>
     *
     * <code>.ConsumeResult consumeResult = 4;</code>
     */
    public int getConsumeResultValue() {
      return consumeResult_;
    }
    /**
     * <pre>
     *消息消费结果
     * </pre>
     *
     * <code>.ConsumeResult consumeResult = 4;</code>
     */
    public com.cookienats.common.papimq.protos.common.Enums.ConsumeResult getConsumeResult() {
      @SuppressWarnings("deprecation")
      com.cookienats.common.papimq.protos.common.Enums.ConsumeResult result = com.cookienats.common.papimq.protos.common.Enums.ConsumeResult.valueOf(consumeResult_);
      return result == null ? com.cookienats.common.papimq.protos.common.Enums.ConsumeResult.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeInt64(1, requestId_);
      }
      if (!getTopicNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topicName_);
      }
      if (!getSubscriberNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subscriberName_);
      }
      if (consumeResult_ != com.cookienats.common.papimq.protos.common.Enums.ConsumeResult.CONSUME_FAIL.getNumber()) {
        output.writeEnum(4, consumeResult_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (!getTopicNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topicName_);
      }
      if (!getSubscriberNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subscriberName_);
      }
      if (consumeResult_ != com.cookienats.common.papimq.protos.common.Enums.ConsumeResult.CONSUME_FAIL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, consumeResult_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReportConsumeResultRequest)) {
        return super.equals(obj);
      }
      ReportConsumeResultRequest other = (ReportConsumeResultRequest) obj;

      boolean result = true;
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && getTopicName()
          .equals(other.getTopicName());
      result = result && getSubscriberName()
          .equals(other.getSubscriberName());
      result = result && consumeResult_ == other.consumeResult_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + TOPICNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTopicName().hashCode();
      hash = (37 * hash) + SUBSCRIBERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriberName().hashCode();
      hash = (37 * hash) + CONSUMERESULT_FIELD_NUMBER;
      hash = (53 * hash) + consumeResult_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReportConsumeResultRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReportConsumeResultRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReportConsumeResultRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReportConsumeResultRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReportConsumeResultRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReportConsumeResultRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReportConsumeResultRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReportConsumeResultRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReportConsumeResultRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReportConsumeResultRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReportConsumeResultRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReportConsumeResultRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReportConsumeResultRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReportConsumeResultRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReportConsumeResultRequest)
        ReportConsumeResultRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReportConsumeResult.internal_static_ReportConsumeResultRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReportConsumeResult.internal_static_ReportConsumeResultRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReportConsumeResultRequest.class, Builder.class);
      }

      // Construct using com.cookienats.common.papimq.protos.msg.consumer.ReportConsumeResult.ReportConsumeResultRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        topicName_ = "";

        subscriberName_ = "";

        consumeResult_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReportConsumeResult.internal_static_ReportConsumeResultRequest_descriptor;
      }

      @Override
      public ReportConsumeResultRequest getDefaultInstanceForType() {
        return ReportConsumeResultRequest.getDefaultInstance();
      }

      @Override
      public ReportConsumeResultRequest build() {
        ReportConsumeResultRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ReportConsumeResultRequest buildPartial() {
        ReportConsumeResultRequest result = new ReportConsumeResultRequest(this);
        result.requestId_ = requestId_;
        result.topicName_ = topicName_;
        result.subscriberName_ = subscriberName_;
        result.consumeResult_ = consumeResult_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReportConsumeResultRequest) {
          return mergeFrom((ReportConsumeResultRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReportConsumeResultRequest other) {
        if (other == ReportConsumeResultRequest.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (!other.getTopicName().isEmpty()) {
          topicName_ = other.topicName_;
          onChanged();
        }
        if (!other.getSubscriberName().isEmpty()) {
          subscriberName_ = other.subscriberName_;
          onChanged();
        }
        if (other.consumeResult_ != 0) {
          setConsumeResultValue(other.getConsumeResultValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReportConsumeResultRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReportConsumeResultRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestId_ ;
      /**
       * <code>int64 requestId = 1;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>int64 requestId = 1;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private Object topicName_ = "";
      /**
       * <code>string topicName = 2;</code>
       */
      public String getTopicName() {
        Object ref = topicName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          topicName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string topicName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTopicNameBytes() {
        Object ref = topicName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          topicName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topicName = 2;</code>
       */
      public Builder setTopicName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topicName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topicName = 2;</code>
       */
      public Builder clearTopicName() {
        
        topicName_ = getDefaultInstance().getTopicName();
        onChanged();
        return this;
      }
      /**
       * <code>string topicName = 2;</code>
       */
      public Builder setTopicNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topicName_ = value;
        onChanged();
        return this;
      }

      private Object subscriberName_ = "";
      /**
       * <code>string subscriberName = 3;</code>
       */
      public String getSubscriberName() {
        Object ref = subscriberName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          subscriberName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string subscriberName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSubscriberNameBytes() {
        Object ref = subscriberName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          subscriberName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subscriberName = 3;</code>
       */
      public Builder setSubscriberName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subscriberName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subscriberName = 3;</code>
       */
      public Builder clearSubscriberName() {
        
        subscriberName_ = getDefaultInstance().getSubscriberName();
        onChanged();
        return this;
      }
      /**
       * <code>string subscriberName = 3;</code>
       */
      public Builder setSubscriberNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subscriberName_ = value;
        onChanged();
        return this;
      }

      private int consumeResult_ = 0;
      /**
       * <pre>
       *消息消费结果
       * </pre>
       *
       * <code>.ConsumeResult consumeResult = 4;</code>
       */
      public int getConsumeResultValue() {
        return consumeResult_;
      }
      /**
       * <pre>
       *消息消费结果
       * </pre>
       *
       * <code>.ConsumeResult consumeResult = 4;</code>
       */
      public Builder setConsumeResultValue(int value) {
        consumeResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息消费结果
       * </pre>
       *
       * <code>.ConsumeResult consumeResult = 4;</code>
       */
      public com.cookienats.common.papimq.protos.common.Enums.ConsumeResult getConsumeResult() {
        @SuppressWarnings("deprecation")
        com.cookienats.common.papimq.protos.common.Enums.ConsumeResult result = com.cookienats.common.papimq.protos.common.Enums.ConsumeResult.valueOf(consumeResult_);
        return result == null ? com.cookienats.common.papimq.protos.common.Enums.ConsumeResult.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息消费结果
       * </pre>
       *
       * <code>.ConsumeResult consumeResult = 4;</code>
       */
      public Builder setConsumeResult(com.cookienats.common.papimq.protos.common.Enums.ConsumeResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        consumeResult_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息消费结果
       * </pre>
       *
       * <code>.ConsumeResult consumeResult = 4;</code>
       */
      public Builder clearConsumeResult() {
        
        consumeResult_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReportConsumeResultRequest)
    }

    // @@protoc_insertion_point(class_scope:ReportConsumeResultRequest)
    private static final ReportConsumeResultRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReportConsumeResultRequest();
    }

    public static ReportConsumeResultRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportConsumeResultRequest>
        PARSER = new com.google.protobuf.AbstractParser<ReportConsumeResultRequest>() {
      @Override
      public ReportConsumeResultRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportConsumeResultRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReportConsumeResultRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReportConsumeResultRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public ReportConsumeResultRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReportConsumeResultResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReportConsumeResultResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CommonResult result = 1;</code>
     */
    int getResultValue();
    /**
     * <code>.CommonResult result = 1;</code>
     */
    com.cookienats.common.papimq.protos.common.Result.CommonResult getResult();
  }
  /**
   * Protobuf type {@code ReportConsumeResultResponse}
   */
  public  static final class ReportConsumeResultResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReportConsumeResultResponse)
      ReportConsumeResultResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReportConsumeResultResponse.newBuilder() to construct.
    private ReportConsumeResultResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportConsumeResultResponse() {
      result_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReportConsumeResultResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReportConsumeResult.internal_static_ReportConsumeResultResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReportConsumeResult.internal_static_ReportConsumeResultResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReportConsumeResultResponse.class, Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.CommonResult result = 1;</code>
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.CommonResult result = 1;</code>
     */
    public com.cookienats.common.papimq.protos.common.Result.CommonResult getResult() {
      @SuppressWarnings("deprecation")
      com.cookienats.common.papimq.protos.common.Result.CommonResult result = com.cookienats.common.papimq.protos.common.Result.CommonResult.valueOf(result_);
      return result == null ? com.cookienats.common.papimq.protos.common.Result.CommonResult.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != com.cookienats.common.papimq.protos.common.Result.CommonResult.SYSTEM_ERROR.getNumber()) {
        output.writeEnum(1, result_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != com.cookienats.common.papimq.protos.common.Result.CommonResult.SYSTEM_ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReportConsumeResultResponse)) {
        return super.equals(obj);
      }
      ReportConsumeResultResponse other = (ReportConsumeResultResponse) obj;

      boolean result = true;
      result = result && result_ == other.result_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReportConsumeResultResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReportConsumeResultResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReportConsumeResultResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReportConsumeResultResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReportConsumeResultResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReportConsumeResultResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReportConsumeResultResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReportConsumeResultResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReportConsumeResultResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReportConsumeResultResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReportConsumeResultResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReportConsumeResultResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReportConsumeResultResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReportConsumeResultResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReportConsumeResultResponse)
        ReportConsumeResultResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReportConsumeResult.internal_static_ReportConsumeResultResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReportConsumeResult.internal_static_ReportConsumeResultResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReportConsumeResultResponse.class, Builder.class);
      }

      // Construct using com.cookienats.common.papimq.protos.msg.consumer.ReportConsumeResult.ReportConsumeResultResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReportConsumeResult.internal_static_ReportConsumeResultResponse_descriptor;
      }

      @Override
      public ReportConsumeResultResponse getDefaultInstanceForType() {
        return ReportConsumeResultResponse.getDefaultInstance();
      }

      @Override
      public ReportConsumeResultResponse build() {
        ReportConsumeResultResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ReportConsumeResultResponse buildPartial() {
        ReportConsumeResultResponse result = new ReportConsumeResultResponse(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReportConsumeResultResponse) {
          return mergeFrom((ReportConsumeResultResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReportConsumeResultResponse other) {
        if (other == ReportConsumeResultResponse.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReportConsumeResultResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReportConsumeResultResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ = 0;
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public int getResultValue() {
        return result_;
      }
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public Builder setResultValue(int value) {
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public com.cookienats.common.papimq.protos.common.Result.CommonResult getResult() {
        @SuppressWarnings("deprecation")
        com.cookienats.common.papimq.protos.common.Result.CommonResult result = com.cookienats.common.papimq.protos.common.Result.CommonResult.valueOf(result_);
        return result == null ? com.cookienats.common.papimq.protos.common.Result.CommonResult.UNRECOGNIZED : result;
      }
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public Builder setResult(com.cookienats.common.papimq.protos.common.Result.CommonResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CommonResult result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReportConsumeResultResponse)
    }

    // @@protoc_insertion_point(class_scope:ReportConsumeResultResponse)
    private static final ReportConsumeResultResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReportConsumeResultResponse();
    }

    public static ReportConsumeResultResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportConsumeResultResponse>
        PARSER = new com.google.protobuf.AbstractParser<ReportConsumeResultResponse>() {
      @Override
      public ReportConsumeResultResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportConsumeResultResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReportConsumeResultResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReportConsumeResultResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public ReportConsumeResultResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportConsumeResultRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportConsumeResultRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportConsumeResultResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportConsumeResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n&msg/consumer/ReportConsumeResult.proto" +
      "\032\023common/Result.proto\032\022common/Enums.prot" +
      "o\"\201\001\n\032ReportConsumeResultRequest\022\021\n\trequ" +
      "estId\030\001 \001(\003\022\021\n\ttopicName\030\002 \001(\t\022\026\n\016subscr" +
      "iberName\030\003 \001(\t\022%\n\rconsumeResult\030\004 \001(\0162\016." +
      "ConsumeResult\"<\n\033ReportConsumeResultResp" +
      "onse\022\035\n\006result\030\001 \001(\0162\r.CommonResultB2\n0c" +
      "om.cookienats.common.papimq.protos.msg.c" +
      "onsumerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cookienats.common.papimq.protos.common.Result.getDescriptor(),
          com.cookienats.common.papimq.protos.common.Enums.getDescriptor(),
        }, assigner);
    internal_static_ReportConsumeResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReportConsumeResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportConsumeResultRequest_descriptor,
        new String[] { "RequestId", "TopicName", "SubscriberName", "ConsumeResult", });
    internal_static_ReportConsumeResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReportConsumeResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportConsumeResultResponse_descriptor,
        new String[] { "Result", });
    com.cookienats.common.papimq.protos.common.Result.getDescriptor();
    com.cookienats.common.papimq.protos.common.Enums.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
