spring:
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /PapiMQ

papimq:
  #PapiMQ服务serverId，不能重复 0~31
  serverId: 0
  #默认0，serverId+dataCenterId不重复即可
  dataCenterId: 0
  #MQ服务地址
  host: localhost
  #MQ服务端口
  port: 9539